version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/LightningTables-core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/LightningTables-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/LightningTables-demo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
